# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crpgdvingmkgn00fc06u/dds_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2024-11-09-r1"

containerPort: 5000

config:
  KAFKA_HOST: "rc1a-h6sike6vhfgi10tg.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "producer_consumer"
  KAFKA_CONSUMER_PASSWORD: "86!L=c3YuZl."
  KAFKA_CONSUMER_GROUP: "dds-service"
  KAFKA_DDS_SERVICE_CONSUMER_TOPIC: "stg-service-orders"
  KAFKA_DDS_SERVICE_PRODUCER_TOPIC: "dds-service-orders"

  PG_WAREHOUSE_HOST: "rc1a-kdbp3o9rxjpy7ghc.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "sprint9dwh"
  PG_WAREHOUSE_USER: "db_user"
  PG_WAREHOUSE_PASSWORD: "86!L=c3YuZl."

  BATCH_SIZE: "100"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi